import Foundation

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
func source(_ path: String) throws -> String {
    try String(contentsOf: root.appendingPathComponent(path), encoding: .utf8)
}

let screen = try source("PeakLog/Views/Today/TodayWorkoutScreen.swift")
let card = try source("PeakLog/Views/Today/PlannedCardioCard.swift")
let sheet = try source("PeakLog/Views/Today/CardioCompletionSheet.swift")
let dailyRecord = try source("PeakLog/Views/Today/DailyRecordSheet.swift")
let addPlan = try source("PeakLog/Views/Today/AddPlanExerciseSheet.swift")
let picker = try source("PeakLog/Views/Today/ExercisePickerScreen.swift")
let recordCard = try source("PeakLog/Views/Today/RunningRecordCard.swift")
let history = try source("PeakLog/Views/History/HistoryCompletedTrainingSection.swift")
let localizations = try source("PeakLog/Localizable.xcstrings")

precondition(screen.contains("CardioCompletionSheet"))
precondition(screen.contains("PlannedCardioCard"))
precondition(screen.contains("exercise.itemType == .cardio"))
precondition(card.contains("targetDurationMinutes"))
precondition(card.contains("targetDistanceKm"))
precondition(!card.contains("targetRPE"))
precondition(card.contains("isCardioCompleted"))
precondition(sheet.contains("activityType.supportsDistance"))
precondition(sheet.contains("CardioMetrics("))
precondition(!card.contains("onAddSet"))
precondition(!sheet.contains("targetReps"))
precondition(dailyRecord.contains("CardioActivityType.allCases"))
precondition(dailyRecord.contains("selectedCardioActivity.supportsDistance"))
precondition(!dailyRecord.contains("rpeText"))
precondition(dailyRecord.contains("case cardio(CardioMetrics)"))
precondition(!addPlan.contains("typePicker"))
precondition(!addPlan.contains("planTypeButton"))
precondition(addPlan.contains("onSelectCardio"))
precondition(picker.contains("case cardio"))
precondition(picker.contains("CardioActivityType.allCases"))
precondition(picker.contains("let onConfirm: ([ExerciseDefinition]) -> Void"))
precondition(picker.contains("onSelectCardio: ((CardioActivityType) -> Void)?"))
precondition(addPlan.contains("PlanExerciseDraft.cardio("))
precondition(addPlan.contains("selectedCardioActivity.supportsDistance"))
precondition(addPlan.contains("cardioSubmissionDrafts"))
precondition(addPlan.contains("save(submissionDrafts)"))
precondition(addPlan.contains(".disabled(cardioSubmissionDrafts == nil || isSaving)"))
precondition(picker.contains("muscleFilter = muscleFilter == group ? nil : group"))
precondition(picker.contains("onSelectCardio == nil") && picker.contains("exercise_picker.activity_title"))
precondition(!localizations.contains("\"add_plan_exercise.strength_subtitle\""))
precondition(!localizations.contains("\"add_plan_exercise.cardio_subtitle\""))
precondition(!localizations.contains("\"cardio.metric.rpe\""))
precondition(!addPlan.contains("cardioRPE"))
precondition(!sheet.contains("rpeText"))
precondition(!recordCard.contains("record.rpe"))
precondition(!history.contains("record.rpe"))
precondition(screen.contains("today.plan.complete_with_rpe"), "Strength completion RPE must remain available")
precondition(history.contains("set.rpe"), "Strength history RPE must remain visible")

print("cardio plan UI contract passed")
