import Foundation

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
func source(_ path: String) throws -> String {
    try String(contentsOf: root.appendingPathComponent(path), encoding: .utf8)
}

let screen = try source("PeakLog/Views/Today/TodayWorkoutScreen.swift")
let card = try source("PeakLog/Views/Today/PlannedCardioCard.swift")
let sheet = try source("PeakLog/Views/Today/CardioCompletionSheet.swift")
let dailyRecord = try source("PeakLog/Views/Today/DailyRecordSheet.swift")
let addPlan = try source("PeakLog/Views/Today/AddPlanExerciseSheet.swift")
let picker = try source("PeakLog/Views/Today/ExercisePickerScreen.swift")
let recordCard = try source("PeakLog/Views/Today/RunningRecordCard.swift")
let planEditing = try source("PeakLog/Views/Today/PlanExerciseEditingComponents.swift")
let history = try source("PeakLog/Views/History/HistoryCompletedTrainingSection.swift")
let localizations = try source("PeakLog/Localizable.xcstrings")
let workoutModels = try source("PeakLog/Models/WorkoutModels.swift")

precondition(screen.contains("CardioCompletionSheet"))
precondition(screen.contains("PlannedCardioCard"))
precondition(screen.contains("exercise.itemType == .cardio"))
precondition(card.contains("targetDurationMinutes"))
precondition(card.contains("targetDistanceKm"))
precondition(!card.contains("targetRPE"))
precondition(card.contains("isCardioCompleted"))
precondition(sheet.contains("activityType.supportsDistance"))
precondition(sheet.contains("CardioMetrics("))
precondition(!card.contains("onAddSet"))
precondition(!sheet.contains("targetReps"))
precondition(dailyRecord.contains("CardioActivityType.allCases"))
precondition(dailyRecord.contains("selectedCardioActivity.supportsDistance"))
precondition(!dailyRecord.contains("rpeText"))
precondition(dailyRecord.contains("case cardio(CardioMetrics)"))
precondition(!addPlan.contains("typePicker"))
precondition(!addPlan.contains("planTypeButton"))
precondition(picker.contains("ExercisePickerItem"))
precondition(picker.contains("CardioActivityType.allCases"))
precondition(picker.contains("let onConfirm: ([ExercisePickerItem]) -> Void"))
precondition(!picker.contains("onSelectCardio"))
precondition(!picker.contains("cardioRows"))
precondition(!picker.contains("chevron.right"))
precondition(picker.contains("pickerRow(for: .cardio(activity)"))
precondition(picker.contains("filteredCardio"))
precondition(picker.contains("selection.map(\\.id)"))
precondition(addPlan.contains("[PlanExerciseFormItem]"))
precondition(addPlan.contains("PlanExerciseDraftBuilder.drafts(items: formItems)"))
precondition(addPlan.contains("CardioPlanFormCard"))
precondition(addPlan.contains("case .cardio"))
precondition(addPlan.contains("Text(\"daily_record.type.cardio\")"), "Cardio form header must show the same type pill as a strength form header")
precondition(addPlan.contains(".fill(Color.accentPrimary)"), "Cardio form header must use the same accent marker as a strength form header")
precondition(addPlan.contains("VStack(spacing: 6)"), "Cardio metrics must use the same content spacing as strength sets")
precondition(addPlan.contains(".padding(.horizontal, 6)"), "Cardio metrics must align with strength form content")
precondition(!addPlan.contains("selectedCardioActivity"))
precondition(!addPlan.contains("cardioDuration"))
precondition(!addPlan.contains("cardioDistance"))
precondition(!addPlan.contains("cardioSubmissionDrafts"))
precondition(!addPlan.contains("case cardioForm"))
precondition(picker.contains("category = .muscle(group)"))
precondition(picker.contains("supportsCardio ? \"exercise_picker.activity_title\" : \"exercise_picker.title\""))
precondition(!localizations.contains("\"add_plan_exercise.strength_subtitle\""))
precondition(!localizations.contains("\"add_plan_exercise.cardio_subtitle\""))
precondition(!localizations.contains("\"cardio.metric.rpe\""))
precondition(!addPlan.contains("cardioRPE"))
precondition(!sheet.contains("rpeText"))
precondition(!recordCard.contains("record.rpe"))
precondition(!history.contains("record.rpe"))
// 力量组的 RPE 完成入口已随 d6823ec 迁到 TodayPlannedSetRow（PlanExerciseEditingComponents.swift），
// TodayWorkoutScreen 通过 TodayPlannedExerciseCard 渲染它。
precondition(planEditing.contains("today.plan.complete_with_rpe"), "Strength completion RPE must remain available")
precondition(screen.contains("TodayPlannedExerciseCard("), "Today screen must still render the strength card that owns the RPE menu")
precondition(history.contains("set.rpe"), "Strength history RPE must remain visible")
precondition(workoutModels.contains("case .running: return String(localized: \"cardio.activity.running\")"))
precondition(workoutModels.contains("case .cycling: return String(localized: \"cardio.activity.cycling\")"))
precondition(workoutModels.contains("case .elliptical: return String(localized: \"cardio.activity.elliptical\")"))
precondition(workoutModels.contains("case .stairClimber: return String(localized: \"cardio.activity.stair_climber\")"))
precondition(!workoutModels.contains("String.LocalizationValue(\"cardio.activity.\\(rawValue)\")"))

print("cardio plan UI contract passed")
