-- Remove weekly plans that the inverted generation window produced a full
-- week early, so the corrected Sunday-evening run can generate them from real
-- data instead of hitting the idempotency check.
--
-- BACKGROUND
-- generate-weekly-plan's window predicate was `weekday !== 0 || hour >= 20`
-- -- the negation of the intended "local Sunday 20:00 or later". That left the
-- window open Monday through Saturday. Because the target week is derived from
-- `now` (nextMondayString), the first tick after local Monday 00:00 targeted a
-- Monday *two* weeks out and generated it immediately. Steady state was:
--
--   Mon 00:00 of week N  ->  installs the plan for week N+1  (week N has zero
--                            training logged; the plan is built from data that
--                            ends at the start of the week before it)
--   Sun 20:00 of week N  ->  plan for week N+1 already exists -> no-op
--
-- so every plan was generated seven days early and never saw the week it was
-- supposed to react to -- the core premise of ADR-001 ("依据本周实际训练与编辑
-- 事件生成下一整周计划").
--
-- WHY ROWS MUST BE DELETED, NOT MARKED
-- Both gates that would otherwise let a corrected run replace the row are
-- status-blind: selectDueUsers / generateForUser query training_plans by
-- (user_id, week_start_date) with no status filter, install_generated_plan
-- raises 'a plan for week % already exists', and idx_training_plans_active_week
-- is UNIQUE on (user_id, week_start_date) regardless of status. Setting
-- status='archived' would leave the week just as blocked.
--
-- SCOPE AND SAFETY
-- Without this cleanup the fix still converges on its own -- exactly one more
-- week is served by a stale pre-generated plan, then the cadence self-heals
-- from the following Sunday. This migration only buys back that one week, so
-- every predicate below is deliberately conservative; a row is removed only if
-- ALL of the following hold:
--
--   1. week_start_date is strictly in the future for that user's own timezone.
--      Mirrors C21 -- the current week and history are never touched.
--   2. It was created before local Sunday 00:00 of the week it targets, i.e.
--      more than 20 hours before the legitimate Sun 20:00-23:59 window could
--      have produced it. A plan generated correctly on Sunday evening can
--      never match; one generated the previous Monday misses by ~7 days.
--      This is what makes the migration safe to apply at any moment,
--      including during a user's Sunday evening.
--   3. Nothing has been completed or linked against it, and no user edit event
--      references it. Vacuously true today -- CloudSnapshotLoader filters
--      week_start_date <= today, so a future plan is invisible to the client
--      and cannot have been touched -- but cheap insurance against ever
--      deleting real work.
--
-- Cascades to training_plan_days / _exercises / _sets (ON DELETE CASCADE).
-- plan_generations and plan_edit_events keep their rows: plan_id there is a
-- plain uuid with no FK, so the provenance trail of what was generated and
-- why survives the cleanup intact.
--
-- Idempotent: re-running finds nothing, because a plan regenerated by the
-- corrected window always fails predicate 2.

DO $$
DECLARE
  v_deleted_count integer := 0;
  v_deleted record;
BEGIN
  FOR v_deleted IN
    WITH candidates AS (
      SELECT
        tp.id,
        tp.user_id,
        tp.week_start_date,
        tp.created_at,
        -- An unrecognized identifier would make AT TIME ZONE raise and abort
        -- the whole migration, so anything Postgres does not know falls back
        -- to UTC (the same default the Edge Function applies).
        COALESCE(
          (SELECT n.name FROM pg_timezone_names n WHERE n.name = prof.timezone),
          'UTC'
        ) AS tz
      FROM training_plans tp
      JOIN profiles prof ON prof.id = tp.user_id
    ),
    premature AS (
      SELECT c.*
      FROM candidates c
      WHERE
        -- (1) strictly future for this user, in their own local clock
        c.week_start_date > date_trunc('week', (now() AT TIME ZONE c.tz))::date
        -- (2) created before local Sunday 00:00 of the week it targets
        AND c.created_at < ((c.week_start_date - 1)::timestamp AT TIME ZONE c.tz)
        -- (3) untouched: nothing completed, nothing linked, no user edits
        AND NOT EXISTS (
          SELECT 1 FROM training_plan_sets s
          WHERE s.plan_id = c.id
            AND (s.completed_at IS NOT NULL OR s.linked_exercise_set_id IS NOT NULL)
        )
        AND NOT EXISTS (
          SELECT 1 FROM training_plan_exercises e
          WHERE e.plan_id = c.id
            AND (e.cardio_completed_at IS NOT NULL OR e.linked_cardio_workout_id IS NOT NULL)
        )
        AND NOT EXISTS (
          SELECT 1 FROM plan_edit_events ev
          WHERE ev.plan_id = c.id AND ev.source = 'user'
        )
    ),
    deleted AS (
      DELETE FROM training_plans tp
      USING premature p
      WHERE tp.id = p.id
      RETURNING tp.user_id, tp.week_start_date, tp.created_at
    )
    SELECT d.user_id, d.week_start_date, d.created_at FROM deleted d
  LOOP
    v_deleted_count := v_deleted_count + 1;
    RAISE NOTICE 'removed prematurely generated plan: user=% week_start=% created_at=%',
      v_deleted.user_id, v_deleted.week_start_date, v_deleted.created_at;
  END LOOP;

  RAISE NOTICE 'cleanup_prematurely_generated_plans: % plan(s) removed; the next local Sunday 20:00 run will regenerate them from real data', v_deleted_count;
END $$;
